/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StoresRouteImport } from './routes/stores'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FinancesRouteImport } from './routes/finances'
import { Route as CategoriesRouteImport } from './routes/categories'
import { Route as AdminUsersRouteImport } from './routes/admin-users'
import { Route as AddRouteImport } from './routes/add'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StoresStoreIdRouteImport } from './routes/stores_.$storeId'
import { Route as ProductsProductIdRouteImport } from './routes/products_.$productId'
import { Route as CategoriesCategoryIdRouteImport } from './routes/categories_.$categoryId'

const StoresRoute = StoresRouteImport.update({
  id: '/stores',
  path: '/stores',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FinancesRoute = FinancesRouteImport.update({
  id: '/finances',
  path: '/finances',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesRoute = CategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin-users',
  path: '/admin-users',
  getParentRoute: () => rootRouteImport,
} as any)
const AddRoute = AddRouteImport.update({
  id: '/add',
  path: '/add',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StoresStoreIdRoute = StoresStoreIdRouteImport.update({
  id: '/stores_/$storeId',
  path: '/stores/$storeId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsProductIdRoute = ProductsProductIdRouteImport.update({
  id: '/products_/$productId',
  path: '/products/$productId',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesCategoryIdRoute = CategoriesCategoryIdRouteImport.update({
  id: '/categories_/$categoryId',
  path: '/categories/$categoryId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/add': typeof AddRoute
  '/admin-users': typeof AdminUsersRoute
  '/categories': typeof CategoriesRoute
  '/finances': typeof FinancesRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/products': typeof ProductsRoute
  '/settings': typeof SettingsRoute
  '/stores': typeof StoresRoute
  '/categories/$categoryId': typeof CategoriesCategoryIdRoute
  '/products/$productId': typeof ProductsProductIdRoute
  '/stores/$storeId': typeof StoresStoreIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/add': typeof AddRoute
  '/admin-users': typeof AdminUsersRoute
  '/categories': typeof CategoriesRoute
  '/finances': typeof FinancesRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/products': typeof ProductsRoute
  '/settings': typeof SettingsRoute
  '/stores': typeof StoresRoute
  '/categories/$categoryId': typeof CategoriesCategoryIdRoute
  '/products/$productId': typeof ProductsProductIdRoute
  '/stores/$storeId': typeof StoresStoreIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/add': typeof AddRoute
  '/admin-users': typeof AdminUsersRoute
  '/categories': typeof CategoriesRoute
  '/finances': typeof FinancesRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/products': typeof ProductsRoute
  '/settings': typeof SettingsRoute
  '/stores': typeof StoresRoute
  '/categories_/$categoryId': typeof CategoriesCategoryIdRoute
  '/products_/$productId': typeof ProductsProductIdRoute
  '/stores_/$storeId': typeof StoresStoreIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/add'
    | '/admin-users'
    | '/categories'
    | '/finances'
    | '/login'
    | '/notifications'
    | '/products'
    | '/settings'
    | '/stores'
    | '/categories/$categoryId'
    | '/products/$productId'
    | '/stores/$storeId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/add'
    | '/admin-users'
    | '/categories'
    | '/finances'
    | '/login'
    | '/notifications'
    | '/products'
    | '/settings'
    | '/stores'
    | '/categories/$categoryId'
    | '/products/$productId'
    | '/stores/$storeId'
  id:
    | '__root__'
    | '/'
    | '/add'
    | '/admin-users'
    | '/categories'
    | '/finances'
    | '/login'
    | '/notifications'
    | '/products'
    | '/settings'
    | '/stores'
    | '/categories_/$categoryId'
    | '/products_/$productId'
    | '/stores_/$storeId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AddRoute: typeof AddRoute
  AdminUsersRoute: typeof AdminUsersRoute
  CategoriesRoute: typeof CategoriesRoute
  FinancesRoute: typeof FinancesRoute
  LoginRoute: typeof LoginRoute
  NotificationsRoute: typeof NotificationsRoute
  ProductsRoute: typeof ProductsRoute
  SettingsRoute: typeof SettingsRoute
  StoresRoute: typeof StoresRoute
  CategoriesCategoryIdRoute: typeof CategoriesCategoryIdRoute
  ProductsProductIdRoute: typeof ProductsProductIdRoute
  StoresStoreIdRoute: typeof StoresStoreIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/stores': {
      id: '/stores'
      path: '/stores'
      fullPath: '/stores'
      preLoaderRoute: typeof StoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finances': {
      id: '/finances'
      path: '/finances'
      fullPath: '/finances'
      preLoaderRoute: typeof FinancesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories': {
      id: '/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-users': {
      id: '/admin-users'
      path: '/admin-users'
      fullPath: '/admin-users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add': {
      id: '/add'
      path: '/add'
      fullPath: '/add'
      preLoaderRoute: typeof AddRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stores_/$storeId': {
      id: '/stores_/$storeId'
      path: '/stores/$storeId'
      fullPath: '/stores/$storeId'
      preLoaderRoute: typeof StoresStoreIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products_/$productId': {
      id: '/products_/$productId'
      path: '/products/$productId'
      fullPath: '/products/$productId'
      preLoaderRoute: typeof ProductsProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories_/$categoryId': {
      id: '/categories_/$categoryId'
      path: '/categories/$categoryId'
      fullPath: '/categories/$categoryId'
      preLoaderRoute: typeof CategoriesCategoryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AddRoute: AddRoute,
  AdminUsersRoute: AdminUsersRoute,
  CategoriesRoute: CategoriesRoute,
  FinancesRoute: FinancesRoute,
  LoginRoute: LoginRoute,
  NotificationsRoute: NotificationsRoute,
  ProductsRoute: ProductsRoute,
  SettingsRoute: SettingsRoute,
  StoresRoute: StoresRoute,
  CategoriesCategoryIdRoute: CategoriesCategoryIdRoute,
  ProductsProductIdRoute: ProductsProductIdRoute,
  StoresStoreIdRoute: StoresStoreIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
