// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Page-local replacement for supabase-js's default navigator.locks-based auth
// lock — see the comment on `lock` below for why. Only serializes calls made
// by this page instance; no cross-tab/cross-reload state, so nothing can be
// left stuck by an interrupted request.
let authLockChain: Promise<unknown> = Promise.resolve();
function pageLocalAuthLock<T>(fn: () => Promise<T>): Promise<T> {
  const result = authLockChain.then(fn, fn);
  authLockChain = result.catch(() => {});
  return result;
}

function createSupabaseClient() {
  // Single source of truth: VITE_SUPABASE_URL / VITE_SUPABASE_PUBLISHABLE_KEY.
  // import.meta.env.VITE_* is inlined at build time (works in the browser).
  // process.env.VITE_* is checked first when available (e.g. request-time env
  // on the server) so it can override a stale build-time value; guarded with
  // `typeof process` because `process` is not polyfilled in the browser bundle.
  const SUPABASE_URL =
    (typeof process !== 'undefined' ? process.env.VITE_SUPABASE_URL : undefined) ??
    import.meta.env.VITE_SUPABASE_URL;
  const SUPABASE_PUBLISHABLE_KEY =
    (typeof process !== 'undefined' ? process.env.VITE_SUPABASE_PUBLISHABLE_KEY : undefined) ??
    import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    const missing = [
      ...(!SUPABASE_URL ? ['VITE_SUPABASE_URL'] : []),
      ...(!SUPABASE_PUBLISHABLE_KEY ? ['VITE_SUPABASE_PUBLISHABLE_KEY'] : []),
    ];
    const message = `Missing Supabase environment variable(s): ${missing.join(', ')}. Connect Supabase in Lovable Cloud.`;
    console.error(`[Supabase] ${message}`);
    throw new Error(message);
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      storage: typeof window !== 'undefined' ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
      // By default supabase-js serializes auth calls (getSession, signIn, token
      // refresh) through navigator.locks — a mutex scoped to the whole browser
      // origin, not just this tab. If a page reloads (or a request is aborted)
      // while that lock is held, it can be left stuck forever, hanging every
      // future login/session call across every tab of this origin until the
      // browser fully releases it. The page-local lock below keeps the same
      // serialization within this page's lifetime without that failure mode.
      lock: (_name, _acquireTimeout, fn) => pageLocalAuthLock(fn),
    }
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});

